### ISSUE TITLE
Recent terms use non-standard IRIs for DCTERMS

### ISSUE THREAD

**Issue by cthoyt** [AnimalGenome/livestock-breed-ontology#1]
https://github.com/AnimalGenome/livestock-breed-ontology/blob/2efe69b9e49aa5fe6591d32392c177438d3d0504/current_release/lbo.obo#L8010-L8024

the most recent 2 terms added should use: http://purl.org/dc/terms/ as the prefix for dcterms

**Comment by caripark** [comment]
@cthoyt thank you for letting us know. This has been corrected.

**Comment by cthoyt** [comment]
Thanks @caripark 

For future reference, this is the commit where these changes were implemented: https://github.com/AnimalGenome/livestock-breed-ontology/commit/116fd5caec8d3f69d6b265c443bdf8da99d2eaf4
